### ISSUE TITLE
Use clang as default compiler

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/OSGeo4A#12]
With android ndk 11, gcc is deprecated and clang is recommended.

**Sidenotes:**
These notes are not directly related to clang but to an update of the toolchain.
- Qt 5.7 requires C++11 features, which must be enabled within cmake
- Qt 5.6 seems to require gcc-4.8 which is only shipped up to ndk 10. If gcc-4.8 is not present qscintilla will fail to compile.

**Comment by m-kuhn** [comment]
Keep an eye on these toolchains:

https://github.com/OSVR/android-cmake/tree/libcxx

**Comment by medspx** [comment]
Hello,

for qscintilla under Qt5.6, you can force ANDROID_NDK_TOOLCHAIN_VERSION variable to match TOOLCHAIN_VERSION. This seems to work for Qt5.6.1 and NDK 13 (at least, it does compile qscintilla): qmake use 4.9 toolchain directory instead of default 4.8.
