### ISSUE TITLE
use openssl 1.0.2 to be able to build qca

### ISSUE THREAD

**Issue by PeterPetrik** [opengisch/OSGeo4A#29]
> we need to use 1.0.2p instead to be able to build qca.
> https://github.com/openssl/openssl/releases/tag/OpenSSL_1_0_2p
> 
> so various libraries moved to support openssl 1.1.x. Unfortunately it seems qca do not have such attention.

**Comment by PeterPetrik** [comment]
see https://github.com/opengisch/OSGeo4A/pull/25

**Comment by m-kuhn** [comment]
thanks @PeterPetrik do you know if there is an upstream issue in qca?

**Comment by PeterPetrik** [comment]
no idea where they have issue tracker, but last release is 20month old and we use it :(
