### ISSUE TITLE
cannot build Proj 5.2

### ISSUE THREAD

**Issue by 3nids** [opengisch/OSGeo4A#35]
see https://github.com/OSGeo/proj.4/issues/1235
and mostly https://github.com/OSGeo/proj.4/issues/1236
it seems nad2bin will be removed in Proj version 6, seems to be due in march 2019.

**Comment by m-kuhn** [comment]
Let's wait and see if it the problem solves itself.
If it becomes urgent, let's add a patch for nad/Makefile.am as suggested by @rouault.

**Comment by 3nids** [comment]
I gave it a try...but modifying the Makefile requires automake-1.16....which isn't available on Xenial....

**Comment by 3nids** [comment]
There is two solutions:
1. use [upcoming](https://github.com/OSGeo/proj.4/commits/6.0) version 6 of Proj since the nad2bin execution has been [removed](https://github.com/OSGeo/proj.4/pull/1248) 
2. hack into nad/Makefile.am to disable the use of nad2bin (I failed when I tried, since I [forgot](https://github.com/OSGeo/proj.4/issues/1235#issuecomment-458443233) to run autogen.sh)

**Comment by m-kuhn** [comment]
It's 5.2 for the moment
https://github.com/opengisch/OSGeo4A/commit/1555b354ee4c4ea4b1224b7d031eadcd16b05098
