### ISSUE TITLE
Map rotation

### ISSUE THREAD

**Issue by catalinmiraute** [opengisch/OSGeo4A#40]
Hi there, I am new in using and promoting Qfield, but I have a first observation and request: please implement a map rotation mecanism/functionality, it will be very helpful to the orientation of users in the field.
Thanks!

**Comment by m-kuhn** [comment]
Hi, thanks for getting in touch.

This would be a nice feature indeed. If you would like to sponsor it, please get in touch with us so we can discuss the details and prepare an offer.

Meanwhile it's added as an enhancement issue in the QField issue tracker https://github.com/opengisch/QField/issues/492
