### ISSUE TITLE
libmagic-mgc_5.32-2ubuntu0.1_amd64.deb not found while building with Docker

### ISSUE THREAD

**Issue by edips** [opengisch/OSGeo4A#47]
When I try to build OSGeo4A with Docker, I get the error:
```
Err:1 http://security.ubuntu.com/ubuntu bionic-updates/main amd64 libmagic-mgc amd64 1:5.32-2ubuntu0.1
  404  Not Found [IP: 91.189.91.23 80]
Err:2 http://security.ubuntu.com/ubuntu bionic-updates/main amd64 libmagic1 amd64 1:5.32-2ubuntu0.1
  404  Not Found [IP: 91.189.91.23 80]
Err:3 http://security.ubuntu.com/ubuntu bionic-updates/main amd64 file amd64 1:5.32-2ubuntu0.1
  404  Not Found [IP: 91.189.91.23 80]
Fetched 179 kB in 1s (165 kB/s)
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/f/file/libmagic-mgc_5.32-2ubuntu0.1_amd64.deb  404  Not Found [IP: 91.189.91.23 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/f/file/libmagic1_5.32-2ubuntu0.1_amd64.deb  404  Not Found [IP: 91.189.91.23 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/f/file/file_5.32-2ubuntu0.1_amd64.deb  404  Not Found [IP: 91.189.91.23 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c apt-get install -y file python3-six zip' returned a non-zero code: 100
```

**Comment by m-kuhn** [comment]
On first sight this looks like a temporary error in ubuntu. Did this happen repeatedly?

**Comment by edips** [comment]
Yes I tried `sudo docker build -t osgeo4a .` and I got the error. I checked the link `http://security.ubuntu.com/ubuntu/pool/main/f/file/libmagic-mgc_5.32-2ubuntu0.1_amd64.deb` it was empty. I was able to build OSGeo4A with docker 2 months ago.

**Comment by m-kuhn** [comment]
Not sure what's going on. Are you aware of https://hub.docker.com/r/opengisch/qfield-sdk/tags where prebuilt docker images can be found?

**Comment by edips** [comment]
I didn't know about the link. I will try them. I tried [this](https://github.com/opengisch/OSGeo4A/blob/master/Dockerfile) docker file.

**Comment by m-kuhn** [comment]
See this section here for more info https://github.com/opengisch/QField/#build (the tag in the script is outdated, replace it with a newer one)

**Comment by edips** [comment]
Thank you. It built a working apk for QField.
