### ISSUE TITLE
GDAL installation problem

### ISSUE THREAD

**Issue by edips** [opengisch/OSGeo4A#54]
Hello. I try to install QGIS libraries with `./distribute.sh -dqgis -mqgis`. GDAL gave error:
```
In file included from ./ogrogdi.h:40:
/usr/include/ogdi/ecs.h:9:10: fatal error: 'rpc/rpc.h' file not found
```
I installed other recipes, then run this  `./distribute.sh -dqgis -mgdal` It gave the same error. I tried Ubuntu 19.10 and 18.04 for ArmV7. [Here](https://paste.ubuntu.com/p/585DVVzWg4/) is the log on terminal. I was able to build it 9 months ago, now I cannot build it on the same Ubuntu 18.04 :)

Platform: Qt 5.12.6, Android NDK r19c, Android SDK 26.1.1

**Comment by m-kuhn** [comment]
Please use the provided Dockerfile to create the binaries.
Or use a prebuilt one https://github.com/opengisch/OSGeo4A/releases

**Comment by edips** [comment]
I tried 20191203 version. I will try again with new prebuilt. I can run QgsQuick app using GIS libraries of Lutra Consulting's docker hub. Map themes didn't work because of OpenSSL on Qt 5.12.6. After using Qt 5.13.0 it is working. I will try to build it from Docker and local OS. I would like to use Qt 12.6 with Osgeo4A because it supports Android 4.3+.

**Comment by m-kuhn** [comment]
I'd recommend building it on top of the QField libs.

**Comment by edips** [comment]
Thank you very much for uploading libraries and other files in Osgeo4A prebuilt. I thought 3 files are the same source code. Now I noticed the prebuilt. I downloaded source code of Osgeo4A before :)

**Comment by m-kuhn** [comment]
Glad it helped :)
For your information, the ndk/sdk and qt libs in use are available for download as well https://github.com/opengisch/docker-qt-ndk/releases

**Comment by edips** [comment]
That's great, I can play with building them with the version of NDK/SDK/Qt versions. I would like to discover the logic of building c++ libraries with bash scripting.

**Comment by m-kuhn** [comment]
Just copy one of the recipes and adjust it to your needs and add it as a dependency in the gdal recipe.
