### ISSUE TITLE
*** No rule to make targe**

### ISSUE THREAD

**Issue by captainsetro** [opengisch/OSGeo4A#65]
*** No rule to make target `/xxxxxx/build-android/build/qgis/7d58502b3b0a615ba1f6a4a8adab5465e18caf56/resources/function_help/json/$$area', needed by `src/core/qgsexpression_texts.cpp'.  Stop.

build on macOS catalina, QT 5.15.0

**Comment by m-kuhn** [comment]
See https://github.com/opengisch/OSGeo4A/issues/63#issuecomment-646250171

**Comment by m-kuhn** [comment]
Likely related to a recent macOS issue of QGIS which has been fixed in qgis master.
